---
title: "FAIR, agil und reproduzierbar – moderner Umgang mit Daten und Analysen im Gesundheitswesen"
author: "Daniel Stekhoven"
date: 2025-03-16
format: 
  html:
    toc: true
    toc-title: Inhalt
    number-sections: true
    number-depth: 2
    embed-resources: true
    code-links:
      - text: "Quellcode auf GitHub"
        icon: github
        href: https://github.com/stekhoven/digitale_biomarker
editor: visual
bibliography: references.bib
---

## Einführung

Dieser Kursabschnitt befasst sich mit modernen Konzepten des Datenmanagements und der Analyse im Gesundheitswesen. Der Fokus liegt auf der Bedeutung der FAIR-Prinzipien [@wilkinson2016], agiler Softwareentwicklung [@beck2001agile] und der Reproduzierbarkeit wissenschaftlicher Analysen [@munafò2017]. Das Skript ist eine Ergänzung zur Vorlesung *FAIR, agil und reproduzierbar – moderner Umgang mit Daten und Analysen im Gesundheitswesen*, welche Teil der Vorlesungsreihe *Digitale Biomarker* im Bachelor Humanmedizin der ETH Zürich ist.

## Herausforderungen im Gesundheitsdaten-Management

Gesundheitsdaten sind komplex, sensibel und oft schwierig zu verwalten. Sie werden deswegen nur selten für Forschung und Entwicklung wiederverwendet [@gaudet-blavignac2021]. Zentrale Herausforderungen umfassen Datenschutz, Interoperabilität zwischen Systemen, Qualitätssicherung und die ständig wachsende Menge an Daten (Big Data) [@abouelmehdi2018].

![Zugriff auf Gesundheitsdaten aus verschiedenen Perspektiven. Abbildung: Helbling[^1]](img/Helbling_Abbildung_1-2144x1528.png){#perspektiven}

[^1]: Die Herausforderung der Datenintegration im Gesundheitswesen aus drei Perspektiven, [Insight, September 2023](https://helbling.ch/de/insights/die-herausforderung-der-datenintegration-im-gesundheitswesen-aus-drei-perspektiven-1)

[^2]: Die Herausforderung der Datenintegration im Gesundheitswesen aus drei Perspektiven, [Insight, September 2023](https://helbling.ch/de/insights/die-herausforderung-der-datenintegration-im-gesundheitswesen-aus-drei-perspektiven-1)

## FAIR-Prinzipien

FAIR steht für Findable (auffindbar), Accessible (zugänglich), Interoperable (kompatibel) und Reusable (wiederverwendbar) [@wilkinson2016]. Diese Prinzipien unterstützen ein effizientes Datenmanagement und fördern den Austausch zwischen Forschenden, insbesondere unabhängig von den verwendeten Infrastrukturen [@mons2017].

![Die FAIR Data Principles legen Kriterien fest, die es ermöglichen, die Philosophie der Offenheit durch moderne Veröffentlichungspraktiken und Infrastrukturen, die die aktuellen Anforderungen der Datenwissenschaft unterstützen, konkret umzusetzen. Abbildung: Cambridge Cristallographic Data Centre (CCDC)[^3]](img/FAIR-Image.png){#FAIR}

[^3]: FAIR Data Principles, <https://www.ccdc.cam.ac.uk/solutions/about-the-csd/fair-data-principles/>

[^4]: FAIR Data Principles, <https://www.ccdc.cam.ac.uk/solutions/about-the-csd/fair-data-principles/>

## FAIR in der Praxis

Die FAIR-Prinzipien ermöglichen, dass Daten einfacher von verschiedenen Akteuren genutzt werden können [@wilkinson2016]. Erfolgreiche Implementierungen der FAIR-Prinzipien führen nachweislich zu erhöhter Forschungsqualität und beschleunigten Entdeckungen [@fairshar2019; @boeckhout2018]. Manchmal sind Daten aber nicht einfach teilbar, dann ist es hilfreich, wenn man die Metadaten teilen kann [@dasilvasantos2023].

#### *Praxisbeispiel: LUMC und SURF in Holland*

Im Medizinischen Zentrum der Universität Leiden (LUMC) wird der FAIR Data Point [FDP, @dasilvasantos2023] eingesetzt, um Metadaten über COVID-Patientendaten im Interesse der Forschung so offen wie möglich zu machen, während die Daten notwendigerweise nicht verfügbar sind und in einer Vielzahl verschiedener Systeme gespeichert werden. Im Gegensatz dazu wendet der niederländische Datendienstleister SURF die FDP an, um die FAIRness eines umfangreichen Datensatzspeichers zu verbessern, der standardmäßig offen zugänglich ist [@whyte2022].

## Agile Softwareentwicklung

Agile Softwareentwicklung beschreibt iterative und flexible Entwicklungsmethoden, welche schnelle Anpassungen und kontinuierliches Feedback ermöglichen. Die Entwicklung erfolgt in kurzen Zyklen (Sprints) und integriert Nutzerfeedback frühzeitig [@beck2001agile; @abrahamsson2002].

![Agile Softwareentwicklung zeichnet sich durch das schrittweise Erarbeiten einer Lösung in mehreren Sprints aus. Abbildung: SolDevolo[^5]](img/Agile-software-dev-1.jpeg.webp){#agile}

[^5]: Is Agile always the best solution for software development projects? <https://soldevelo.com/blog/is-agile-always-the-best-solution-for-software-development-projects/>

[^6]: Is Agile always the best solution for software development projects? <https://soldevelo.com/blog/is-agile-always-the-best-solution-for-software-development-projects/>

## Besonderheiten der Softwareentwicklung im Gesundheitswesen

Im Gesundheitswesen stellen regulatorische Vorgaben, Datenschutzbestimmungen und hohe Anforderungen an Datensicherheit besondere Herausforderungen für die Softwareentwicklung dar [@mcgraw2021]. Diese müssen bereits in frühen Entwicklungsphasen berücksichtigt werden und auf pragmatische, auf die Endnutzer ausgerichtete Produkte hervorbringen [@mathews2019].

Es gibt aber auch noch andere Punkte, die einen grossen Einfluss haben:

1.  Unzureichende Strategie und Ausführungsplan 
2.  Fehlende Akzeptanz bei den Beteiligten 
3.  Die Last veralteter Prozesse 
4.  Veraltete Systeme und Schwierigkeiten bei der Integration mit neuen Technologien 
5.  Fehlende Priorisierung von Schulung und Einführung

Diese Punkte werden als einige der grössten Herausforderungen bei der digitalen Transformation verstanden[^7]. Sie gelten eins zu eins für die Entwicklung von Software im Gesundheitswesen.

[^7]: Die 5 größten Herausforderungen bei der digitalen Transformation, DECODE, 15. Juni 2023, <https://www.zoho.com/de/creator/decode/top-5-digital-transformation-herausforderungen>

## Reproduzierbarkeit in Analysen

Reproduzierbarkeit bedeutet, dass wissenschaftliche Ergebnisse und Analysen durch unabhängige Forschende nachvollzogen und verifiziert werden können. Fehlende Reproduzierbarkeit führt oft zu Unsicherheiten, Verzögerungen und Verschwendung von Ressourcen [@ioannidis2005]. Seit vielen Jahren befindet sich die Forschung in eine regelrechten Reproduzierbarkeitskrise [@baker2016; @nosek2022; @errington2021]. Die Gemeinschaft reagiert zaghaft darauf und Initiativen zur Förderung von rigoroser, transparenter und reproduzierbarer Forschung sind entstanden [for instance @fromgra2021].

![(A) Diagramm, in dem jeder Kreis einen Effekt darstellt, für den eine SMD-Effektgrösse sowohl für den ursprünglichen Effekt als auch für die Replikation berechnet werden konnte (n=110). Blaue Kreise zeigen Effekte an, für die p\<0.05 in der Replikation war, und rote Kreise zeigen p\>0.05 an. Zwei Effekte, für die die ursprüngliche Effektgröße \>80 war, sind nicht dargestellt. Der Median der Effektgrösse in den Replikationen war 85% kleiner als der Median der Effektgrösse in den ursprünglichen Experimenten, und 97% der Effektgrössen in den Replikationen waren kleiner als die ursprünglichen Effektgrössen (unterhalb der grauen diagonalen Linie). (B) Eine erweiterte Ansicht von Feld A für Effektgrössen \< 5 (grauer Umriss in Feld A). SMD: Standard Mean Differenz. [Abbildung: @errington2021]](img/lax_71601_elife-71601-fig2-v3.tif.jpg){#reproducibility}

## Vorteile der Reproduzierbarkeit

Reproduzierbare Forschung erhöht die Vertrauenswürdigkeit, Qualität und Effizienz wissenschaftlicher Arbeit, da Ergebnisse und Analysen unabhängig überprüft werden können [@munafò2017; @peng2011; @cobey2024]. Im Gesundheitswesen verbessert Reproduzierbarkeit die klinische Entscheidungsfindung und stärkt die Grundlage für evidenzbasierte Medizin [@niven2018]. Interoperabilität, als wesentliche Komponente der Reproduzierbarkeit, ermöglicht zudem den Austausch und die Nutzung von Daten und Ergebnissen über verschiedene Systeme und Organisationen hinweg, was die Zusammenarbeit zwischen Forschungseinrichtungen, Kliniken und Industriepartnern vereinfacht und dadurch Innovation und medizinische Fortschritte beschleunigt [@gaudet-blavignac2021]. Insgesamt fördert reproduzierbare Forschung Transparenz, minimiert Fehlerpotenziale und reduziert unnötige Kosten und Ressourcenverschwendung [@freedman2015].
